[tool.poetry]
name = "fastevent"
version = "0.0.0"  # version managed by tool.poetry-dynamic-versioning
description = "Event programming framework."
authors = [
    "Sam Pegler <jobs@sampegler.co.uk>",
]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
azure-servicebus = "^7.14.2"
pydantic = "^2.11"
python = "^3.12"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
mypy = "^1.9.0"
pytest = "^8.1.1"
pytest-asyncio = "^1.1.0"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.1"
pytest-random-order = "^1.1.1"
pyupgrade = "^3.20.0"
ruff = "^0.3.5"
testcontainers = "^4.10.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
bump = false
metadata = false
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"
format-jinja = """
    {%- if branch == "main" and distance == 0 -%}
        {{ base }}
    {%- elif branch == "main" -%}
        {{ bump_version(base) }}-b{{ distance }}
    {%- else -%}
        {{ bump_version(base) }}-dev{{ distance }}+{{ branch_escaped }}
    {%- endif -%}
"""

[tool.poetry-dynamic-versioning.substitution]
files = ["fastevent/__init__.py"]

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    "*.pyi"
]
line-length = 88

[tool.ruff.lint]
ignore = []
select = [
    "C9",
    "E",
    "F",
    "W",
]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
